name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set environment variables
        run: |
          echo "IMAGE_TAG=0.0.${{ github.run_number }}" >> $GITHUB_ENV
          echo "checking image tag, is: ${{env.IMAGE_TAG}}"

      - name: Modify deploy-k8s.yaml file to use new image tag
        run: |
          sed -i "s|image: crazyguy888/k8s-flasktest:.*|image: crazyguy888/k8s-flasktest:${{env.IMAGE_TAG}}|" deploy-k8s.yaml

      - name: install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: SCP yaml to remote machine using sshpass
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: | 
          sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no ./deploy-k8s.yaml $SSH_USER@$REMOTE_HOST:/home/$SSH_USER

      - name: SSH and apply kubernetes yaml
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$REMOTE_HOST "kubectl apply -f /home/$SSH_USER/deploy-k8s.yaml"
          